name: PHPUnit GitHub Actions Test

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: src

jobs:
  run-test:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel-bookmark
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Migrate And Setup
        run: cp .env.ci .env && php artisan key:generate && php artisan migrate && php artisan db:seed --class=DatabaseSeeder && chmod -R 777 storage

      - name: Run test suite
        run: composer run-script test